# Generated by Django 5.2.1 on 2025-05-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_tour_available_slots_alter_tour_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['-start_date'], 'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['start_date'], 'verbose_name': 'Тур', 'verbose_name_plural': 'Туры'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='num_people',
            field=models.IntegerField(verbose_name='Количество человек'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено'), ('completed', 'Завершено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='images',
            field=models.ManyToManyField(blank=True, to='tours.image', verbose_name='Изображения отеля'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название отеля'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='stars',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Количество звёзд'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='tour_images/', verbose_name='Файл изображения'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='promotions', to='tours.country', verbose_name='Страны по акции'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.TextField(verbose_name='Описание акции'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название акции'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='tours',
            field=models.ManyToManyField(blank=True, related_name='promotions', to='tours.tour', verbose_name='Туры по акции'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Оценка'),
        ),
    ]
